# Generated by Django 5.2.8 on 2026-06-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgen', '0002_alter_alert_id_alter_alerthospital_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('nale', 'male'), ('female', 'female')], max_length=10),
        ),
    ]
